### ISSUE TITLE
can't load module into studio after build is success

### ISSUE THREAD

**Issue by ajaytiwa** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#52]
Build was successful but I can't load the connector 0.3.0 into studio.

I have disabled below xml from original pom.xml

	

Failed to resolve module com.mule.mulechain:mulechain-ai-connector:0.3.0 (hover for more details or open this problem's Properties)
Resolving dependency com.mule.mulechain:mulechain-ai-connector found the following exceptions:
java.lang.RuntimeException: There was an issue solving the dependencies for the bundleDescriptors [[BundleDescriptor{groupId='com.mule.mulechain', artifactId='mulechain-ai-connector', baseVersion='null', version='0.3.0', type='jar', classifier=Optional[mule-plugin], systemPath=Optional.empty}]]
	at org.mule.maven.client.internal.MuleMavenClient.resolvePluginBundleDescriptorsDependencies(MuleMavenClient.java:376)
	at org.mule.tooling.core.m2.internal.MuleMavenClientResolver.resolvePluginDependencies(MuleMavenClientResolver.java:78)
	at org.mule.tooling.core.module.internal.runner.DownloadTask.doRun(DownloadTask.java:76)
	at org.mule.tooling.core.module.internal.runner.Task.run(Task.java:65)
	at org.mule.tooling.core.module.internal.runner.DownloadTask.run(DownloadTask.java:1)
	at org.mule.tooling.core.module.internal.runner.SingleDownloadTask.run(SingleDownloadTask.java:1)
	at org.mule.tooling.core.module.internal.runner.ArtifactResolvingRunner$ArtifactJob.run(ArtifactResolvingRunner.java:225)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at com.mule.mulechain:mulechain-ai-connector:jar:mule-plugin:0.3.0
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:363)
	at org.mule.maven.client.internal.MuleMavenClient.doResolveDependencies(MuleMavenClient.java:485)
	at org.mule.maven.client.internal.MuleMavenClient.doResolveDependencies(MuleMavenClient.java:428)
	at org.mule.maven.client.internal.MuleMavenClient.resolvePluginBundleDescriptorsDependencies(MuleMavenClient.java:372)
	... 7 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.mule.mulechain:mulechain-ai-connector:jar:mule-plugin:0.3.0
	at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:260)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328)
	... 10 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.mule.mulechain:mulechain-ai-connector:jar:mule-plugin:0.3.0
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:242)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:172)
	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382)
	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368)
	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218)
	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156)
	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138)
	at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108)
	at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222)
	... 12 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: com.mule.mulechain:mulechain-ai-connector:pom:0.3.0 (absent): com.mule.mulechain:mulechain-ai-connector:pom:0.3.0 was not found in https://maven.anypoint.mulesoft.com/api/v3/maven during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of anypoint-exchange-v3 has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:473)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:231)
	... 20 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: com.mule.mulechain:mulechain-ai-connector:pom:0.3.0 was not found in https://maven.anypoint.mulesoft.com/api/v3/maven during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of anypoint-exchange-v3 has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:225)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:201)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:586)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:525)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
	... 23 more

**Comment by amirkhan-ak-sf** [comment]
@arpitg-1 could you please look into this?

**Comment by amirkhan-ak-sf** [comment]
@ajaytiwa Can you share with you application pom.xml ?

**Comment by ajaytiwa** [comment]
**Studio POM**

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.mycompany</groupId>
	<artifactId>mule-ai1</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>mule-application</packaging>

	<name>mule-ai1</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<app.runtime>4.3.0-20230417</app.runtime>
		<mule.maven.plugin.version>4.1.0</mule.maven.plugin.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.2.0</version>
			</plugin>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>1.7.3</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<version>1.2.3</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mule.mulechain</groupId>
			<artifactId>mulechain-ai-connector</artifactId>
			<version>0.3.0</version>
			<classifier>mule-plugin</classifier>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>



**Connector POM**

Note:  I had to comment some section due to same error I also experienced.
https://github.com/MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector/issues/33

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.mule.mulechain</groupId>
	<artifactId>mulechain-ai-connector</artifactId>
	<version>0.3.0</version>
	<packaging>mule-extension</packaging>
	<name>MuleSoft AI Chain Connector - Mule 4</name>

	<parent>
		<groupId>org.mule.extensions</groupId>
		<artifactId>mule-modules-parent</artifactId>
		<version>1.3.2</version>
	</parent>
	
    <properties>
        <muleJavaEeBomVersion>4.6.0</muleJavaEeBomVersion>
		<formatterConfigPath>formatter.xml</formatterConfigPath>
		<javaFormatter.plugin.version>2.0.1</javaFormatter.plugin.version>
		<formatterGoal>validate</formatterGoal>
		<slf4jApi.version>2.0.7</slf4jApi.version>
		<mule.sdk.api.version>0.9.0-rc1</mule.sdk.api.version>
		<langchain4j.version>0.31.0</langchain4j.version>
		<mapdb.version>3.1.0</mapdb.version>
		<json.version>20240303</json.version>
		<munit.input.directory>src/test/munit</munit.input.directory>
		<munit.output.directory>${basedir}/target/test-mule/munit</munit.output.directory>
		<munit.extensions.maven.plugin.version>1.2.0</munit.extensions.maven.plugin.version>
		<jacoco.version>0.8.12</jacoco.version>
    </properties>

	<build>
		<plugins>
		
			<plugin>
				<groupId>net.revelc.code.formatter</groupId>
				<artifactId>formatter-maven-plugin</artifactId>
				<version>${javaFormatter.plugin.version}</version>
				<configuration>
					<compilerCompliance>${javaVersion}</compilerCompliance>
					<compilerSource>${javaVersion}</compilerSource>
					<compilerTargetPlatform>${javaVersion}</compilerTargetPlatform>
					<configFile>${basedir}/${formatterConfigPath}</configFile>
					<configJsFile>${basedir}/${formatterConfigPath}</configJsFile>
					<aggregator>false</aggregator>
					<executionRoot>true</executionRoot>
				</configuration>
				<executions>
					<execution>
						<id>apply-format</id>
						<phase>compile</phase>
						<goals>
							<goal>${formatterGoal}</goal>
						</goals>
						<configuration>
							<skipFormatting>${skipVerifications}</skipFormatting>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit</groupId>
				<artifactId>munit-extensions-maven-plugin</artifactId>
				<version>${munit.extensions.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<argLines>
						<argLine>
							-javaagent:${settings.localRepository}/org/jacoco/org.jacoco.agent/${jacoco.version}/org.jacoco.agent-${jacoco.version}-runtime.jar=destfile=${session.executionRootDirectory}/target/jacoco-munit.exec
						</argLine>
					</argLines>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>org.jsoup</groupId>
							<artifactId>jsoup</artifactId>
						</sharedLibrary>
					</sharedLibraries>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>${jacoco.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<goals>
							<goal>test</goal>
						</goals>
						<phase>integration-test</phase>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.mule</groupId>
                <artifactId>mule-javaee-runtime-bom</artifactId>
                <version>${muleJavaEeBomVersion}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.mule.sdk</groupId>
            <artifactId>mule-sdk-api</artifactId>
            <version>${mule.sdk.api.version}</version>
        </dependency> 
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-open-ai</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4jApi.version}</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>${langchain4j.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>jsoup</artifactId>
					<groupId>org.jsoup</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-embeddings-all-minilm-l6-v2</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-mistral-ai</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mapdb</groupId>
			<artifactId>mapdb</artifactId>
			<version>${mapdb.version}</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>${json.version}</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-document-parser-apache-tika</artifactId>
			<version>${langchain4j.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>log4j-api</artifactId>
					<groupId>org.apache.logging.log4j</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-ollama</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-anthropic</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-azure-open-ai</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-easy-rag</artifactId>
			<version>${langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>io.reactivex.rxjava2</groupId>
			<artifactId>rxjava</artifactId>
			<version>2.2.21</version>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<version>3.2.1</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>3.2.1</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<version>1.2.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>mule-releases</id>
			<name>Nexus Public Releases</name>
			<url>https://repository-master.mulesoft.org/nexus/content/repositories/releases/</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>mulesoft release repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
</project>

**Comment by arpitg-1** [comment]
Hi,

What is the java version that we are using?
Do we have the mulechain-ai-connector version 0.3.0 in .m2 repository? If present please delete it & then rebuild the application again on this version 0.3.0 (mvn clean install -DskipTests). Once successful please clear studio cache or restart anypoint studio.

**Comment by ajaytiwa** [comment]
I am using below java version.

openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.16+8-adhoc..jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.16+8-adhoc..jdk11u, mixed mode)

<img width="518" alt="image" src="https://github.com/user-attachments/assets/ed12c937-a63d-4141-b2d2-7b5c39816d28">

Restarted as well still same error

**Comment by amirkhan-ak-sf** [comment]
@ajaytiwa, the logs look good. Can you please install it again and send us the complete installation log?

**Comment by ajaytiwa** [comment]
[debug logs.log](https://github.com/user-attachments/files/16967427/debug.logs.log)
Attaching the debug logs for your reference

**Comment by chiewklee** [comment]
hi @ajaytiwa ,
do u have the following in your Mule app's POM file?
1. in the build plugin section
						
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>org.jsoup</groupId>
							<artifactId>jsoup</artifactId>
						</sharedLibrary>
					</sharedLibraries>
					<classifier>mule-application</classifier>
				</configuration>
			</plugin>

2. in the dependency section

		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.16.1</version>
		</dependency>
		
Can u add them and see if that helps to resolve the issue. Thanks.

**Comment by arpitg-1** [comment]
Hi @ajaytiwa ,
What is the maven "Base command line for builds" in studio? It will be under Preferences > Anypoint Studio > Maven

**Comment by alick888** [comment]
Hi @ajaytiwa , seems like you are using an old Anypoint Studio and your app.runtime is 4.3.0.  First you can try is to use a newer app.runtime (I'm using 4.7.2) in your pom.xml and see if that helps.  Otherwise, it might be better to update your Anypoint Studio (I'm using 7.18.1)

**Comment by ajaytiwa** [comment]
@alick888  
Studio My Studio version
Version: 7.17.0
Build Id: 202403191428

@arpitg-1 
I used below command to build module.

mvn clean install -Dmaven.test.skip=true -DskipTests -Djdeps.multiRelease=11

In Anypoint studio I have below settings

<img width="646" alt="image" src="https://github.com/user-attachments/assets/4f8c41fe-0ff0-4406-9cbd-54abcdd79e5d">
@amirkhan-ak-sf 

I added dependencies and plugin but this doesn't helped

**Comment by amirkhan-ak-sf** [comment]
By disabling the jdeps plug only and compiling with Java 8 solved the issue. 

Disable this plugin: 
`<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-jdeps-plugin</artifactId>
			<version>3.1.2</version>
			
				<execution>
					<goals>
						<goal>jdkinternals</goal>  
						<goal>test-jdkinternals</goal> 
					</goals>
				</execution>
			</executions>
			<configuration>
				<failOnWarning>false</failOnWarning>
			</configuration>
		</plugin>`

**Comment by ajaytiwa** [comment]
yes ,I confirm ;after disabling code in original pom solved the issue.
